[package]
name = "champagne-winapi"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
champagne-kernel.workspace = true
champagne-loader.workspace = true
champagne-macros.workspace = true
der-parser.workspace = true
digest.workspace = true
inventory.workspace = true
libc.workspace = true
md-5.workspace = true
nix.workspace = true
rand.workspace = true
parking_lot.workspace = true
sha1.workspace = true
sha2.workspace = true
time.workspace = true
tracing.workspace = true
widestring.workspace = true
